// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure that matches our schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
	public: {
		Tables: {
			users: {
				Row: {
					id: string;
					email: string;
					full_name: string;
					phone_number: string | null;
					initials: string;
					type: 'management' | 'holder' | 'merchant' | 'unassigned';
					status: 'pending' | 'approved' | 'suspended';
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id: string;
					email: string;
					full_name: string;
					phone_number?: string | null;
					initials: string;
					type?: 'management' | 'holder' | 'merchant' | 'unassigned';
					status?: 'pending' | 'approved' | 'suspended';
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					email?: string;
					full_name?: string;
					phone_number?: string | null;
					initials?: string;
					type?: 'management' | 'holder' | 'merchant' | 'unassigned';
					status?: 'pending' | 'approved' | 'suspended';
					created_at?: string;
					updated_at?: string;
				};
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			[_ in never]: never;
		};
		Enums: {
			user_status: 'pending' | 'suspended' | 'approved';
			user_type: 'unassigned' | 'merchant' | 'holder' | 'management';
		};
	};
}
